### PR TITLE
Patch tag.py post route & TagModel name property

### PR DESCRIPTION
**Pull request by Justin-f-Reeves**
Thanks for considering my PR! 
Following up from #106, I'm submitting a new PR in a different branch with 2 commits - the first addresses the if-statement issue across 24 files, the second addresses the TagModel.name (unique=False) change across 39 files.

### CODE REVIEW

**Review by LUS24 — APPROVED** [review]
Looks good

**Review by LUS24 — APPROVED** [review]
Looks good too.

**Comment by jslvtr** [comment]
Thank you @Justin-f-Reeves ! Really appreciate the contribution. I've merged it now!

**Comment by Justin-f-Reeves** [comment]
my pleasure. great course - keep up the great work!

**Pull request merged**
