### PR TITLE
bug(typo): change .value to .values in dictionary method call

### PR DESCRIPTION
**Pull request by LUS24**
Changed `value` to `values` to solve the error `AttributeError: 'dict' object has no attribute 'value'`

### CODE REVIEW

**Comment by jslvtr** [comment]
Thank you @LUS24 ! Did you check if this typo is also on any of the lectures or other projects? 🤔

**Comment by LUS24** [comment]
> Thank you @LUS24 ! Did you check if this typo is also on any of the lectures or other projects? 🤔

I haven't yet.

**Comment by LUS24** [comment]
Here I found two more ocurrences:
https://github.com/tecladocode/rest-apis-flask-python/search?q=items.value%28%29

I'll add them to the PR

**Comment by LUS24** [comment]
Added another PR to fix the other typo: https://github.com/tecladocode/rest-apis-flask-python/pull/75

**Pull request merged**
