### PR TITLE
Updated files to match lecture videos, see COU-300

### PR DESCRIPTION
**Pull request by LUS24**

### CODE REVIEW

**Comment by jslvtr** [comment]
Thanks @LUS24 ! I think the template itself should also be renamed to `action.html` instead of `registration.html` 🤔

**Comment by LUS24** [comment]
> Thanks @LUS24 ! I think the template itself should also be renamed to `action.html` instead of `registration.html` 🤔

Yes, the code is in a submodule, and not in the current repo, here is the link to the PR: [LINK](https://github.com/tecladocode/rest-api-smorest-docker/pull/3/files).

Check the linear card for an extra comment about the submodule.

**Comment by jslvtr** [comment]
There's a `registration.html` and `registration.original.html` in the `end` folder of 12/06, and in both `start` and `end` folders of 12/07. Should these be renamed?

**Comment by LUS24** [comment]
Found them!

**Pull request merged**
